### ISSUE TITLE
BTT Octopus V1.1 + BTT U2C + BTT EBB2040 with katapult. Can't get mainboard uuid after all the installations.

### ISSUE THREAD

**Issue by mutlubasdas** [Esoterical/voron_canbus#29]
Hi there,
First of all thanks for the guide, it's really good.

Let me start by explaining what I've done so far.

1. CAN adapter
   1.1 - I flashed the new firmware to the can adapter (U2C).
   1.2 - I needed to add sudo btw :) 

2. Mainboard
   2.1 - I flashed katapult per the Octopus instructions. I realized that the screenshot of the menuconfig for Octopus has "Build Katapult deployment application" set to "32 KiB bootloader" but the readme says to keep it at "do not build". But I still went with the 32 KiB bootloader as shown for my board.
   2.2 - I installed USB-CAN-Bridge Klipper through katapult.
   2.3 - I followed the next steps and I got the uuid for it.

3. Toolhead
   3.1 - I flashed katapult per the Biqu SB2040 instructions. The screenshot for the Biqu SB2040 had "Build Katapult deployment application" set to "8 KiB bootloader" and that's how I did it.
   3.2 - Wired up the all the components,
       3.2.1 - rpi(USB-A) to U2C(USB-C)
       3.2.2 - U2C(USB-A) to Octopus(USB-C)
       3.2.3 - U2C(microfit) to EBB2040(CAN-Cable)
   3.3 - I followed the next steps and to the uuid for it but I only got the toolhead uuid, didn't show the mainboard uuid.
   3.4 - I still followed the next steps and installed klipper through katapult.

I keep getting the dreaded " mcu 'mcu': Unable to connect ".

I tried the printer.old method as recommended in the troubleshooting section.

I can't get the mainboard to show for some reason, I tried using other USB cables (for this -> U2C(USB-A) to Octopus(USB-C) connection) but nothing seems to work.

I can only get the toolhead uuid what the hell did I do wrong :)) it's really weird :) help me out please.

**Comment by Esoterical** [comment]
This isn't the best place for "help me" requests, it's just clunky and theres a good chance no-one (even me) will ever check here. I frequent the voron discord MCU toolhead channel a lot though https://discord.com/channels/460117602945990666/1076243803947667516

But while I'm here, I'll guess your problem is you flashed usb-can-brdige mode klipper ot the octo as per my guide, but you're also using a u2c. You don't want to do that. Either use usb-can-bridge klipper on the octo and then plug the PI to octo via USB and EBB to octo via RJ11, **or** you use the u2c, leave the octo in normal klipper mode USB'd to the pi, then have pi to u2c via usb and then u2c to ebb via CAN.

The first page of the guide makes this distinction, but you may have missed that.

**Comment by mutlubasdas** [comment]
Thanks for the suggestions, I'll follow up at discord.
